resources:
  repositories:
  - repository: azure_template
    type: github
    name: bernardopacini/.azure
    endpoint: bernardopacini

variables:
  REPO_NAME: idwarp
  COMPLEX: true
  GCC_CONFIG: config/defaults/config.LINUX_GFORTRAN_OPENMPI.mk
  INTEL_CONFIG: config/defaults/config.LINUX_INTEL_OPENMPI.mk
  INPUT_FILES: true
  STYLE_CHECK: true

pool:
    vmImage: 'ubuntu-latest'



jobs:
- job:
  parameters:
    - name: TestMatrix
      type: object
      default:
        c7-gcc-ompi-latest:
          DOCKER_TAG: c7-gcc-ompi-latest
          CONFIG_FILE: ${{ variables.GCC_CONFIG }}
        c7-intel-impi-latest:
          DOCKER_TAG: c7-intel-impi-latest
          CONFIG_FILE: ${{ variables.INTEL_CONFIG }}
        u20-gcc-ompi-latest:
          DOCKER_TAG: u20-gcc-ompi-latest
          CONFIG_FILE: ${{ variables.GCC_CONFIG }}
        u20-gcc-ompi-stable:
          DOCKER_TAG: u20-gcc-ompi-stable
          CONFIG_FILE: ${{ variables.GCC_CONFIG }}
  strategy:
    matrix: ${{ parameters.TestMatrix  }}
  steps:
  - script: echo here
    # script: echo {{ parameters.TestMatrix }}
    # - template: before-install.yaml@azure_template
  #   parameters: 
  #     REPO_NAME: ${{ variables.REPO_NAME }}
  #     COMPLEX: ${{ variables.COMPLEX }}
  #     GCC_CONFIG: ${{ variables.GCC_CONFIG }}
  #     INTEL_CONFIG: ${{ variables.INTEL_CONFIG }}
  #     INPUT_FILES: ${{ variables.INPUT_FILES }}
  #     STYLE_CHECK: ${{ variables.STYLE_CHECK }}

  # - template: style_check.yaml@azure_template
  #   parameters:
  #     REPO_NAME: ${{ variables.REPO_NAME }}
  #     STYLE_CHECK: ${{ variables.STYLE_CHECK }}

