resources:
  repositories:
  - repository: azure_template
    type: github
    name: bernardopacini/.github
    endpoint: bernardopacini

extends:
  template: azure/azure_template.yaml@azure_template
  parameters:
    REPO_NAME: idwarp
    IGNORE_STYLE: false
    COMPLEX: true
    GCC_CONFIG: config/defaults/config.LINUX_GFORTRAN_OPENMPI.mk
    INTEL_CONFIG: config/defaults/config.LINUX_INTEL_OPENMPI.mk
    INPUT_FILES: true
    STEPS_MAKE_REAL: make
    STEPS_INSTALL_REAL: pip install .
    STEPS_TEST_REAL: testflo -v . -n 1
    STEPS_MAKE_COMPLEX: make && make -f Makefile_CS PETSC_ARCH=complex-opt-\$COMPILERS-\$PETSCVERSION
    STEPS_INSTALL_COMPLEX: pip install .
    STEPS_TEST_COMPLEX: testflo -v . -n 1