variables:
  REPO_NAME: idwarp
  COMPLEX: false
  GCC_CONFIG: config/defaults/config.LINUX_GFORTRAN_OPENMPI.mk
  INTEL_CONFIG: config/defaults/config.LINUX_INTEL_OPENMPI.mk
  EXEC_TESTS: >
      'docker exec app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd ${{ variables.DOCKER_WORKING_DIR }}/input_files && ./get-input-files.sh"'
      'docker exec app /bin/bash -c ". \$HOME/.bashrc_mdolab && cd ${{ variables.DOCKER_WORKING_DIR/tests }} && testflo . -v -n 1"'

pool:
    vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: azure_template
    type: github
    name: bernardopacini/.azure
    endpoint: bernardopacini

jobs:
  - template: azure_template.yaml@azure_template
    parameters:
      REPO_NAME: ${{ variables.REPO_NAME }}
      COMPLEX: ${{ variables.COMPLEX }}
      GCC_CONFIG: ${{ variables.GCC_CONFIG }}
      INTEL_CONFIG: ${{ variables.INTEL_CONFIG }}
      EXEC_TESTS: ${{ variables.EXEC_TESTS }}