variables:
  REPO_NAME: idwarp
  COMPLEX: true
  GCC_CONFIG: config/defaults/config.LINUX_GFORTRAN_OPENMPI.mk
  INTEL_CONFIG: config/defaults/config.LINUX_INTEL_OPENMPI.mk
  INPUT_FILES: true
  STYLE_CHECK: true

variables:
  - template: matrix.yaml@azure_template

pool:
    vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: azure_template
    type: github
    name: bernardopacini/.azure
    endpoint: bernardopacini


jobs:
  - job:
  strategy:
    matrix: ${{ variables.matrix }}
    steps:
    - template: before-install.yaml@azure_template
  #   parameters: 
  #     REPO_NAME: ${{ variables.REPO_NAME }}
  #     COMPLEX: ${{ variables.COMPLEX }}
  #     GCC_CONFIG: ${{ variables.GCC_CONFIG }}
  #     INTEL_CONFIG: ${{ variables.INTEL_CONFIG }}
  #     INPUT_FILES: ${{ variables.INPUT_FILES }}
  #     STYLE_CHECK: ${{ variables.STYLE_CHECK }}

  # - template: style_check.yaml@azure_template
  #   parameters:
  #     REPO_NAME: ${{ variables.REPO_NAME }}
  #     STYLE_CHECK: ${{ variables.STYLE_CHECK }}

