variables:
  REPO_NAME: idwarp
  COMPLEX: true
  GCC_CONFIG: config/defaults/config.LINUX_GFORTRAN_OPENMPI.mk
  INTEL_CONFIG: config/defaults/config.LINUX_INTEL_OPENMPI.mk
  INPUT_FILES: true


pool:
    vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: azure_template
    type: github
    name: bernardopacini/.azure
    endpoint: bernardopacini

jobs:
  - template: azure_template.yaml@azure_template
    parameters:
      REPO_NAME: ${{ variables.REPO_NAME }}
      COMPLEX: ${{ variables.COMPLEX }}
      GCC_CONFIG: ${{ variables.GCC_CONFIG }}
      INTEL_CONFIG: ${{ variables.INTEL_CONFIG }}  
      INPUT_FILES: ${{ variables.INPUT_FILES }}